### ISSUE TITLE
major- main page - поменять иконку

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#1]
<img width="300" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/6c9b6b1f-543f-48b8-a8e8-b4e2901d2bb5">

**Comment by hoolisoftware** [comment]
На какую?

**Comment by bageus** [comment]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/81c1b1fc-e9a5-4dab-86fc-6e55a48abf6b)
