### ISSUE TITLE
major - силуэты фигур

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#10]
<img width="1424" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/b211990b-db15-4b4a-a50b-37f64676dbc3">

**Comment by hoolisoftware** [comment]
Хотелось бы понять детальнее что с фигурами не так

**Comment by bageus** [comment]
мы это уже обсуждали 
фогуры как в воздухе висят - в макете нижнего шва не видно


![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/c151e888-3299-4221-84cb-57fcf46528c2)

**Comment by bageus** [comment]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/e4633776-ad53-4256-9fc6-0f5a68953b5c)
