### ISSUE TITLE
major - hover

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#11]
<img width="239" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/5c7b34be-61cc-49eb-8aca-af793a5ea30f">

**Comment by bageus** [comment]
<img width="562" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/ca7e039a-567b-4e12-b9a6-4b75ddde67d4">

**Comment by bageus** [comment]
<img width="153" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/c2f21d00-4f0a-4edf-8f35-1bca6cfcf2d7">

**Comment by bageus** [comment]
<img width="202" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/a0a4152e-536b-4e45-b2d6-74ecd6a8af1d">

**Comment by bageus** [comment]
<img width="425" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/a96c8341-8ed9-4ad9-94b9-ffc697cb3f04">

**Comment by bageus** [comment]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/b6073944-c337-40bd-822f-d877a957cdb3)



![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/86f92a79-235b-43aa-91b1-43d0a0afb60c)

**Comment by hoolisoftware** [comment]
Кнопки Add network нельзя подсвечивать потому что иконки будут сливаться с белым фоном

**Comment by bageus** [comment]
я проверял на макете - все норм

**Comment by bageus** [comment]
у save нет ховера

![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/331fb1dc-2b62-4e47-9fa6-1d09cfcb54f1)
