### ISSUE TITLE
major- player account - добавить страницу при нажатии на иконку аккаунта, выполнить какркас со вкладками

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#17]
<img width="761" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/16ee7a89-85e7-4b36-8a0d-313ee288114d">

**Comment by hoolisoftware** [comment]
Не было включено в этап

**Comment by bageus** [comment]
обрати внимание на то что я скидывал там видно все что нужно и не нужное единственное что отсутствовало в макете на момент выдачи это дропдауны - но я написал в тз что они вот вот должны быть, еще писал про вкладку с point system - но ее сделали совсем недавно - поэтому она пойдет в следующий этап
