### ISSUE TITLE
major - settings - убрать кнопку в меню settings - должна быть в меню Player account

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#21]
<img width="1482" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/dc08efea-8e09-4eb5-8ff8-38141a3d847b">

**Comment by bageus** [comment]
<img width="1479" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/ca97f6e8-e399-41ce-b5c2-5930714fa9a0">

**Comment by hoolisoftware** [comment]
``
