### ISSUE TITLE
major- сделай что бы в этом меню кнопки с дропдаун открывался при нажатии

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#33]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/62b46916-c923-4ffa-b38d-d64ff35d24cc)

**Comment by hoolisoftware** [comment]
Просто обычно на сайтах такие меню при наведении работают, если подтверждаете можно поменять

**Comment by bageus** [comment]
обсудили этот момент в переписке, если при нажатии не будет обновляться страница то в целом можно так и оставить
