### ISSUE TITLE
major- wallets - так не должно быть

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#37]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/6d227563-82f2-4f26-b70e-d57a167697f1)

**Comment by hoolisoftware** [comment]
Мы же обсуждали что не стоит вытягивать блок проектов во всю ширину, или я не так понял что-то?

**Comment by bageus** [comment]
но так же тоже не может быть - это уродство какие то
