### ISSUE TITLE
major- добавить сеть

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#38]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/af587a17-8006-49d3-8c32-f1ee27915f74)

**Comment by hoolisoftware** [comment]
Не понимаю как работает данный компонент, нужно больше информации

**Comment by bageus** [comment]
другая последовательность

![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/674c122b-9252-40ba-abd3-ca8bfc1e0ebe)
