### ISSUE TITLE
major- добавить кнопку

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#41]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/3e07818b-77a9-4846-9fd5-b6cabb4ba4ca)

**Comment by hoolisoftware** [comment]
Нарисуйте отдельное окно где показана логика работы правой сексии хедера

![Image](https://github.com/hoolisoftware/ursus-planet/assets/64575343/2efec36e-ed1d-4cca-9fcd-f723e31db8dc)

**Comment by hoolisoftware** [comment]
Кнопку пришлось немного уменьшить в ширине, т.к. в адаптиве не влазила
