### ISSUE TITLE
major- отсутпы сильно большие - часть 1/10 часть страницы съедается

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#5]
<img width="1673" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/d220c981-d4dc-4927-9596-03c4fc95cdd7">

**Comment by hoolisoftware** [comment]
Вы просили сделать максимальную ширину 1250, я и сделал

**Comment by bageus** [comment]
вообще то ты сказал что есть какие то проблемы с этим - я сказал сделать тогда так но я не знал что будет такая "шляпа"

**Comment by hoolisoftware** [comment]
Будем думать как решить эту шляпу ближе к финишу этапа, пока начну с более простых задач

**Comment by bageus** [comment]
я тебе кидал сайт galxe.com у них как бы нестандартный размер контейнера
я почитал и твою статью, и дуругие - но там не до конца раскрыто чем черевато использовать небезопасную ширину, + сложилось ощущение что эти статьи малость устарели т.е эта безопасная зона оставленная побокам обычно использовалась под размещение различный банеров с рекламой

**Comment by hoolisoftware** [comment]
Хорошо, будем эскпериментировать. Оставлю задачу на конец.
