### ISSUE TITLE
major - съехали кнопки

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#50]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/d04adf6a-2088-4bb6-b451-4abe719db5b6)

**Comment by hoolisoftware** [comment]
Так там структура блоков разная, эти кнопки не должны быть на одном уровне

**Comment by bageus** [comment]
ладно не критично пускай будет так 
только текст исправь


![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/b5557448-aad1-4165-9d20-655194694d85)
