### ISSUE TITLE
major - улучшить фоновое изображение

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#52]
![Image](https://github.com/hoolisoftware/ursus-planet/assets/36338626/f37d4028-accc-4a43-9e36-6bfeef6ee5d7)

**Comment by hoolisoftware** [comment]
Для этого мне нужно что бы в макете был предоставлено более качественное изображение

**Comment by bageus** [comment]
так я тебе показывал что там качество максимальное - ты в верстке используешь только часть этого изображения
