### ISSUE TITLE
minor - нужно сделать что бы переключалось

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#6]
<img width="318" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/9a92ffbd-766e-43b3-9268-05097e062d7a">

**Comment by bageus** [comment]
и оставить курсор на Upcoming

**Comment by hoolisoftware** [comment]
Как я понял можно переключиться только на прошлый и следующий сезон.

К примеру если текущий сезон это 21, можно переключиться на 22 и 20, а 1-2-3 и т.д. нельзя?

В этом случае пояснений не нужно, кидайте задачу в беклог.

**Comment by bageus** [comment]
дизайнер недослал этот слайд - но это в любом случае не относится к этой задаче
в этой задаче я прошу сделать интерактивным переключение по этим строка - т.е я навожу мышкой на last season - появляется hover (подсветка букв) и при клике меняется на состояние Active (синяя иконка, белые буквы черная подложка)

а в целом по вопросу 
1 этапом идет анонс сезона Upcoming season - Active на этом пункте справа будут расписаны условия, указан приз и дата начала сезона, 
2 этап в день когда запуститься сезон к примеру 1 он перейдет из upcoming в current - а в upcoming появится новый сезон к примеру 2 
3 этап текущая игра завершилась и попадает в last из upcoming в current и цепочка замкнулась

что бы посмотреть старые сезоны в last  будет кнопка archive можно будет пощелкать (как раз этот слайд и отсутсвует в макете)
