### ISSUE TITLE
major - исправить форму 

### ISSUE THREAD

**Issue by bageus** [hoolisoftware/ursus-planet#8]
<img width="421" alt="изображение" src="https://github.com/hoolisoftware/ursus-planet/assets/36338626/68b34ef5-8033-4c92-b722-c361dc339805">

**Comment by hoolisoftware** [comment]
Форма должна была заработать, если не работает нужно разбираться потому что у меня в браузере отображается иначе чем на предоставленном вами скриншоте

**Comment by bageus** [comment]
она заработала
переноси в done
